import { PrismaClient } from '@prisma/client';

type CategorySpec = string[] | { [name: string]: CategorySpec };

export async function seedCategories(prisma: PrismaClient) {
  console.log('🌱 Seeding Global Categories (idempotent upserts)...');

  const categoriesToSeed: { name: string; description: string; children: CategorySpec }[] = [
    {
      name: 'Food & Beverage',
      description: 'Restaurants, cafes, groceries, and food stalls',
      children: {
        Food: {
          Bakery: [
            'Bread',
            'Cakes',
            'Pastries',
            'Cookies',
            'Muffins',
            'Donuts',
            'Pies & Tarts',
            'Buns & Rolls',
          ],
          'Dairy & Eggs': [
            'Milk',
            'Cheese',
            'Yogurt',
            'Butter',
            'Cream',
            'Eggs',
            'Cream Cheese',
            'Milk Alternatives',
          ],
          Meat: [
            'Beef',
            'Pork',
            'Chicken',
            'Turkey',
            'Lamb',
            'Goat',
            'Processed Meat',
            'Deli Meat',
          ],
          Seafood: [
            'Fish',
            'Shellfish',
            'Shrimp',
            'Crab',
            'Lobster',
            'Crayfish',
            'Mollusks',
            'Cephalopods',
            'Processed Seafood',
            'Dried Seafood',
          ],
          'Grains & Cereals': [
            'Rice',
            'Wheat',
            'Oats',
            'Corn',
            'Barley',
            'Quinoa',
            'Cereal',
            'Other Grains',
          ],
          'Pasta & Noodles': [
            'Pasta',
            'Instant Noodles',
            'Fresh Noodles',
            'Dried Noodles',
            'Rice Noodles',
            'Egg Noodles',
            'Asian Noodles',
          ],
          Snacks: [
            'Chips & Crisps',
            'Crackers',
            'Popcorn',
            'Nuts & Seeds',
            'Dried Fruits',
            'Snack Bars',
            'Pretzels',
            'Savory Snacks',
          ],
          'Sweets & Desserts': [
            'Chocolate',
            'Candy',
            'Ice Cream',
            'Frozen Desserts',
            'Cakes & Pastries',
            'Puddings',
            'Jellies & Gummies',
            'Dessert Mixes',
          ],
          'Frozen Food': [
            'Frozen Meat',
            'Frozen Seafood',
            'Frozen Vegetables',
            'Frozen Fruits',
            'Frozen Meals',
            'Frozen Snacks',
            'Frozen Desserts',
            'Frozen Bakery',
          ],
          'Canned Food': [
            'Canned Vegetables',
            'Canned Fruits',
            'Canned Meat',
            'Canned Seafood',
            'Canned Beans',
            'Canned Soups',
            'Canned Sauces',
            'Canned Meals',
          ],
          'Ready-to-Eat Food': [
            'Ready Meals',
            'Sandwiches',
            'Wraps',
            'Salads',
            'Soups',
            'Rice Meals',
            'Noodle Meals',
            'Prepared Snacks',
          ],
          'Baby Food': [
            'Infant Formula',
            'Baby Cereals',
            'Baby Purees',
            'Baby Snacks',
            'Baby Meals',
            'Baby Drinks',
          ],
        },
        Beverage: {
          Water: [
            'Bottled Water',
            'Mineral Water',
            'Spring Water',
            'Purified Water',
            'Sparkling Water',
            'Flavored Water',
          ],
          Juices: [
            'Fruit Juice',
            'Vegetable Juice',
            'Juice Drinks',
            'Nectar',
            'Cold-Pressed Juice',
            'Concentrated Juice',
          ],
          'Soft Drinks': [
            'Soda',
            'Cola',
            'Lemon-Lime Drinks',
            'Root Beer',
            'Tonic Water',
            'Sparkling Drinks',
          ],
          Coffee: [
            'Coffee Beans',
            'Ground Coffee',
            'Instant Coffee',
            'Cold Brew',
            'Ready-to-Drink Coffee',
            'Coffee Concentrates',
          ],
          Tea: [
            'Black Tea',
            'Green Tea',
            'White Tea',
            'Herbal Tea',
            'Fruit Tea',
            'Milk Tea',
            'Iced Tea',
            'Tea Concentrates',
          ],
          'Energy Drinks': [
            'Energy Drinks',
            'Energy Shots',
            'Energy Powders',
            'Caffeinated Drinks',
          ],
          'Sports Drinks': [
            'Electrolyte Drinks',
            'Isotonic Drinks',
            'Hydration Drinks',
            'Sports Drink Powders',
          ],
          'Milk & Dairy Drinks': [
            'Fresh Milk',
            'Flavored Milk',
            'Chocolate Milk',
            'Yogurt Drinks',
            'Milkshakes',
            'Dairy-Based Drinks',
          ],
          'Plant-Based Drinks': [
            'Soy Milk',
            'Almond Milk',
            'Oat Milk',
            'Coconut Milk',
            'Rice Milk',
            'Other Plant-Based Milk',
          ],
          'Alcoholic Drinks': [
            'Beer',
            'Wine',
            'Gin',
            'Brandy',
            'Vodka',
            'Rum',
            'Soju',
            'Whisky',
            'Tequila',
            'Champagne',
            'Cocktails',
            'Liqueurs',
            'Cider',
            'Sake',
          ],
        },
        'Fresh Produce': {
          Fruits: [
            'Tropical Fruits',
            'Citrus Fruits',
            'Berries',
            'Stone Fruits',
            'Melons',
            'Apples & Pears',
            'Grapes',
            'Bananas',
          ],
          Vegetables: [
            // Cruciferous
            'Broccoli',
            'Cauliflower',
            'Cabbage',
            'Brussels Sprouts',
            'Kale',
            'Bok Choy',
            'Napa Cabbage',
            'Mustard Greens',
            'Collard Greens',
            'Kohlrabi',
            'Radish',
            'Turnip',
            'Watercress',
            // Nightshades
            'Tomato',
            'Eggplant',
            'Bell Pepper',
            'Chili Pepper',
            'Jalapeño',
            'Potato',
            'Sweet Pepper',
            'Ground Cherry',
            // Squash
            'Zucchini',
            'Yellow Squash',
            'Butternut Squash',
            'Acorn Squash',
            'Spaghetti Squash',
            'Kabocha Squash',
            'Pumpkin',
            'Chayote',
            'Delicata Squash',
            'Hubbard Squash',
            // Pod / beans
            'Green Beans',
            'Snow Peas',
            'Sugar Snap Peas',
            'Garden Peas',
            'Okra',
            'Winged Beans',
            'Soybeans / Edamame',
            'Broad Beans / Fava Beans',
            // Bulbs
            'Onion',
            'Red Onion',
            'White Onion',
            'Yellow Onion',
            'Shallot',
            'Garlic',
            'Leek',
            'Fennel',
            // Stems
            'Celery',
            'Asparagus',
            'Rhubarb',
            'Bamboo Shoots',
            'Hearts of Palm',
            'Fiddlehead Ferns',
            // Corn
            'Sweet Corn',
            'White Corn',
            'Yellow Corn',
            'Baby Corn',
          ],
          'Leafy Greens': [
            'Lettuce',
            'Spinach',
            'Kale',
            'Cabbage',
            'Mustard Greens',
            'Water Spinach',
            'Other Leafy Greens',
          ],
          'Root Vegetables': [
            'Potatoes',
            'Sweet Potatoes',
            'Carrots',
            'Radishes',
            'Turnips',
            'Beets',
            'Cassava',
            'Taro',
            'Yams',
          ],
          Herbs: [
            'Basil',
            'Cilantro',
            'Parsley',
            'Mint',
            'Rosemary',
            'Thyme',
            'Oregano',
            'Other Fresh Herbs',
          ],
          Mushrooms: [
            'Button Mushrooms',
            'Oyster Mushrooms',
            'Shiitake Mushrooms',
            'Enoki Mushrooms',
            'Portobello Mushrooms',
            'Other Mushrooms',
          ],
          'Fresh Legumes': ['Green Beans', 'Peas', 'Edamame', 'Soybeans', 'Other Fresh Legumes'],
          'Fresh Nuts': ['Coconut', 'Peanuts', 'Almonds', 'Cashews', 'Walnuts', 'Other Fresh Nuts'],
        },
        Packaged: {
          'Packaged Snacks': ['Chips', 'Crackers', 'Popcorn', 'Nuts', 'Snack Bars', 'Cookies'],
          'Packaged Sweets': ['Chocolate', 'Candy', 'Gummies', 'Marshmallows', 'Packaged Desserts'],
          'Packaged Bakery': [
            'Packaged Bread',
            'Packaged Cakes',
            'Packaged Cookies',
            'Packaged Pastries',
            'Packaged Donuts',
          ],
          'Packaged Grains': ['Rice', 'Cereal', 'Oats', 'Quinoa', 'Other Packaged Grains'],
          'Packaged Pasta & Noodles': [
            'Dry Pasta',
            'Instant Noodles',
            'Dried Noodles',
            'Rice Noodles',
            'Pasta Kits',
          ],
          'Canned & Jarred Food': [
            'Canned Vegetables',
            'Canned Fruits',
            'Canned Meat',
            'Canned Seafood',
            'Jarred Food',
            'Preserved Food',
          ],
          'Instant Food': [
            'Instant Noodles',
            'Instant Rice',
            'Instant Soups',
            'Instant Meals',
            'Instant Breakfast',
          ],
          'Frozen Packaged Food': [
            'Frozen Meals',
            'Frozen Snacks',
            'Frozen Meat',
            'Frozen Seafood',
            'Frozen Vegetables',
            'Frozen Desserts',
          ],
          'Dried Food': [
            'Dried Fruits',
            'Dried Vegetables',
            'Dried Meat',
            'Dried Seafood',
            'Dried Beans',
            'Dehydrated Meals',
          ],
          'Packaged Meat': ['Processed Meat', 'Cured Meat', 'Smoked Meat', 'Sausages', 'Deli Meat'],
          'Packaged Seafood': [
            'Canned Fish',
            'Dried Seafood',
            'Smoked Seafood',
            'Cured Seafood',
            'Processed Seafood',
          ],
        },
        Prepared: {
          Meals: ['Breakfast Meals', 'Lunch Meals', 'Dinner Meals', 'Combo Meals', 'Family Meals'],
          'Rice Meals': ['Rice Bowls', 'Fried Rice', 'Rice Plates', 'Rice Combos'],
          'Noodle Dishes': [
            'Pasta Dishes',
            'Stir-Fried Noodles',
            'Soup Noodles',
            'Rice Noodle Dishes',
          ],
          'Sandwiches & Wraps': ['Sandwiches', 'Burgers', 'Wraps', 'Subs', 'Toast & Paninis'],
          Salads: [
            'Vegetable Salads',
            'Fruit Salads',
            'Pasta Salads',
            'Meat Salads',
            'Seafood Salads',
          ],
          Soups: ['Vegetable Soups', 'Meat Soups', 'Seafood Soups', 'Noodle Soups', 'Cream Soups'],
          'Ready-to-Eat Snacks': [
            'Finger Foods',
            'Fried Snacks',
            'Savory Snacks',
            'Sweet Snacks',
            'Street Food',
          ],
          Desserts: [
            'Cakes',
            'Pastries',
            'Ice Cream',
            'Puddings',
            'Fruit Desserts',
            'Frozen Desserts',
          ],
          'Bakery & Pastries': ['Bread', 'Cakes', 'Pastries', 'Cookies', 'Donuts', 'Pies & Tarts'],
          'Catering & Party Food': [
            'Party Platters',
            'Meal Trays',
            'Dessert Trays',
            'Snack Trays',
            'Buffet Meals',
          ],
        },
        Ingredients: {
          'Grains & Rice': [
            'White Rice',
            'Brown Rice',
            'Sticky Rice',
            'Jasmine Rice',
            'Basmati Rice',
            'Whole Grains',
          ],
          Flour: [
            'All-Purpose Flour',
            'Bread Flour',
            'Cake Flour',
            'Whole Wheat Flour',
            'Rice Flour',
            'Corn Flour',
            'Gluten-Free Flour',
          ],
          'Sugar & Sweeteners': [
            'White Sugar',
            'Brown Sugar',
            'Powdered Sugar',
            'Coconut Sugar',
            'Honey',
            'Syrups',
            'Sugar Alternatives',
          ],
          Salt: ['Table Salt', 'Sea Salt', 'Rock Salt', 'Himalayan Salt', 'Seasoned Salt'],
          'Spices & Seasonings': [
            'Whole Spices',
            'Ground Spices',
            'Spice Blends',
            'Seasoning Mixes',
            'Bouillon & Stock',
          ],
          'Cooking Oils': [
            'Vegetable Oil',
            'Olive Oil',
            'Coconut Oil',
            'Canola Oil',
            'Sesame Oil',
            'Sunflower Oil',
            'Specialty Oils',
          ],
          'Sauces & Condiments': [
            'Soy Sauce',
            'Vinegar',
            'Ketchup',
            'Mayonnaise',
            'Hot Sauce',
            'Cooking Sauces',
            'Dips',
            'Dressings',
          ],
          'Baking Ingredients': [
            'Baking Powder',
            'Baking Soda',
            'Yeast',
            'Cocoa',
            'Chocolate Chips',
            'Food Coloring',
            'Cake Mixes',
            'Decorating Supplies',
          ],
          'Dairy Ingredients': [
            'Milk Powder',
            'Cream',
            'Butter',
            'Cheese',
            'Condensed Milk',
            'Evaporated Milk',
          ],
          'Meat Ingredients': [
            'Fresh Meat',
            'Processed Meat',
            'Ground Meat',
            'Marinated Meat',
            'Meat Seasonings',
          ],
          'Seafood Ingredients': [
            'Fresh Fish',
            'Shellfish',
            'Dried Seafood',
            'Seafood Paste',
            'Seafood Seasonings',
          ],
          Herbs: ['Fresh Herbs', 'Dried Herbs', 'Herb Blends'],
          'Food Additives': [
            'Preservatives',
            'Thickeners',
            'Stabilizers',
            'Emulsifiers',
            'Food Coloring',
            'Flavoring',
          ],
        },
      },
    },
    {
      name: 'Fashion & Cosmetics',
      description: 'Apparel, accessories, jewelry, beauty, and personal care products',
      children: {
        Clothing: {
          "Men's Clothing": [
            'Shirts',
            'T-Shirts',
            'Polo Shirts',
            'Pants',
            'Jeans',
            'Shorts',
            'Suits',
            'Jackets',
            'Sweaters',
            'Underwear',
            'Sleepwear',
            'Activewear',
            'Swimwear',
          ],
          "Women's Clothing": [
            'Tops',
            'T-Shirts',
            'Blouses',
            'Dresses',
            'Skirts',
            'Pants',
            'Jeans',
            'Shorts',
            'Jumpsuits',
            'Jackets',
            'Sweaters',
            'Underwear',
            'Lingerie',
            'Sleepwear',
            'Activewear',
            'Swimwear',
          ],
          "Kids' Clothing": [
            'Tops',
            'Bottoms',
            'Dresses',
            'Sets',
            'Outerwear',
            'Sleepwear',
            'Activewear',
            'Swimwear',
          ],
          'Baby Clothing': [
            'Bodysuits',
            'Rompers',
            'Baby Tops',
            'Baby Bottoms',
            'Baby Dresses',
            'Sleepwear',
            'Outerwear',
          ],
        },
        Shoes: {
          "Men's Shoes": [
            'Sneakers',
            'Dress Shoes',
            'Boots',
            'Sandals',
            'Loafers',
            'Slippers',
            'Athletic Shoes',
            'Casual Shoes',
          ],
          "Women's Shoes": [
            'Sneakers',
            'Heels',
            'Flats',
            'Boots',
            'Sandals',
            'Loafers',
            'Slippers',
            'Athletic Shoes',
          ],
          "Kids' Shoes": [
            'Sneakers',
            'School Shoes',
            'Sandals',
            'Boots',
            'Slippers',
            'Athletic Shoes',
          ],
          'Specialty Footwear': [
            'Work Boots',
            'Safety Shoes',
            'Hiking Shoes',
            'Sports Shoes',
            'Water Shoes',
          ],
        },
        Bags: {
          Handbags: ['Shoulder Bags', 'Crossbody Bags', 'Tote Bags', 'Clutches', 'Satchel Bags'],
          Backpacks: [
            'School Backpacks',
            'Laptop Backpacks',
            'Travel Backpacks',
            'Hiking Backpacks',
          ],
          'Travel Bags': ['Duffel Bags', 'Luggage', 'Suitcases', 'Travel Organizers'],
          'Wallets & Small Bags': ['Wallets', 'Card Holders', 'Coin Purses', 'Pouches'],
        },
        Accessories: {
          Headwear: ['Caps', 'Hats', 'Beanies', 'Headbands'],
          Belts: ['Leather Belts', 'Casual Belts', 'Dress Belts'],
          'Scarves & Gloves': ['Scarves', 'Gloves', 'Mittens'],
          'Hair Accessories': ['Hair Clips', 'Hair Ties', 'Headbands', 'Hair Bows'],
          'Fashion Accessories': ['Sunglasses', 'Keychains', 'Brooches', 'Pins'],
        },
        Jewelry: {
          Necklaces: ['Chains', 'Pendants', 'Chokers', 'Lockets'],
          Earrings: ['Stud Earrings', 'Hoop Earrings', 'Drop Earrings', 'Dangle Earrings'],
          Bracelets: ['Chain Bracelets', 'Bangle Bracelets', 'Charm Bracelets'],
          Rings: ['Fashion Rings', 'Band Rings', 'Statement Rings'],
          'Jewelry Sets': ['Necklace Sets', 'Earring Sets', 'Matching Sets'],
        },
        Watches: {
          'Wrist Watches': [
            'Analog Watches',
            'Digital Watches',
            'Automatic Watches',
            'Quartz Watches',
          ],
          Smartwatches: ['Fitness Smartwatches', 'Sports Smartwatches', 'Lifestyle Smartwatches'],
          'Watch Accessories': ['Watch Straps', 'Watch Bands', 'Watch Cases'],
        },
        Beauty: {
          Makeup: ['Face Makeup', 'Eye Makeup', 'Lip Makeup', 'Cheek Makeup', 'Makeup Sets'],
          Skincare: [
            'Cleansers',
            'Moisturizers',
            'Serums',
            'Face Masks',
            'Sunscreen',
            'Toners',
            'Exfoliators',
          ],
          Haircare: ['Shampoo', 'Conditioner', 'Hair Treatments', 'Hair Styling', 'Hair Color'],
          'Body Care': ['Body Wash', 'Body Lotion', 'Body Scrubs', 'Hand Care', 'Foot Care'],
          Fragrances: ['Perfume', 'Eau de Toilette', 'Cologne', 'Body Mist', 'Fragrance Sets'],
          'Nail Care': ['Nail Polish', 'Nail Treatments', 'Nail Extensions', 'Nail Care Sets'],
          'Personal Care': ['Deodorants', 'Shaving Products', 'Feminine Care', 'Oral Care'],
          'Beauty Tools': [
            'Makeup Brushes',
            'Makeup Sponges',
            'Mirrors',
            'Facial Tools',
            'Hair Styling Tools',
            'Nail Tools',
          ],
        },
      },
    },
    {
      name: 'Electronics',
      description: 'Gadgets, appliances, and tech accessories',
      children: {
        'Mobile Devices': ['Phones', 'Tablets', 'E-Readers', 'Mobile Accessories'],
        Computers: [
          'Laptops',
          'Desktop Computers',
          'Monitors',
          'Computer Components',
          'Computer Accessories',
        ],
        Audio: ['Headphones', 'Earphones', 'Speakers', 'Microphones', 'Audio Equipment'],
        Cameras: [
          'Digital Cameras',
          'Video Cameras',
          'Action Cameras',
          'Camera Lenses',
          'Camera Accessories',
        ],
        Gaming: [
          'Gaming Consoles',
          'Gaming Controllers',
          'Gaming Headsets',
          'Gaming Keyboards',
          'Gaming Mice',
          'Gaming Accessories',
        ],
        'Home Entertainment': [
          'Televisions',
          'Projectors',
          'Media Players',
          'Streaming Devices',
          'Home Theater Equipment',
        ],
        'Smart Devices': [
          'Smartwatches',
          'Fitness Trackers',
          'Smart Home Devices',
          'Smart Speakers',
          'Smart Displays',
          'Wearable Devices',
        ],
        Appliances: [
          'Kitchen Appliances',
          'Home Appliances',
          'Climate Appliances',
          'Cleaning Appliances',
          'Personal Appliances',
        ],
        'Electronics Accessories': [
          'Chargers',
          'Cables',
          'Adapters',
          'Power Banks',
          'Power Strips',
          'Storage Devices',
          'Protective Accessories',
        ],
      },
    },
    {
      name: 'Home & Living',
      description: 'Furniture, hardware, and home improvement',
      children: {
        Furniture: [
          'Living Room Furniture',
          'Bedroom Furniture',
          'Dining Furniture',
          'Office Furniture',
          'Outdoor Furniture',
          'Storage Furniture',
        ],
        'Home Decor': [
          'Wall Decor',
          'Decorative Objects',
          'Rugs & Carpets',
          'Curtains & Blinds',
          'Mirrors',
          'Clocks',
        ],
        'Kitchen & Dining': [
          'Cookware',
          'Bakeware',
          'Tableware',
          'Drinkware',
          'Kitchen Utensils',
          'Food Storage',
        ],
        'Bedding & Bath': [
          'Bedding',
          'Mattresses',
          'Pillows',
          'Towels',
          'Bath Accessories',
          'Bathroom Textiles',
        ],
        'Storage & Organization': [
          'Storage Containers',
          'Shelving',
          'Closet Organization',
          'Drawer Organizers',
          'Laundry Storage',
        ],
        Lighting: ['Ceiling Lights', 'Lamps', 'Wall Lights', 'Outdoor Lighting', 'Light Bulbs'],
        Hardware: [
          'Fasteners',
          'Locks & Security Hardware',
          'Handles & Hinges',
          'Brackets',
          'Building Hardware',
        ],
        Tools: ['Hand Tools', 'Power Tools', 'Measuring Tools', 'Tool Sets', 'Workshop Equipment'],
        'Building Materials': [
          'Lumber',
          'Cement & Concrete',
          'Roofing Materials',
          'Flooring Materials',
          'Wall Materials',
          'Insulation',
        ],
        'Paint & Supplies': [
          'Interior Paint',
          'Exterior Paint',
          'Primers',
          'Paint Tools',
          'Paint Accessories',
        ],
        Plumbing: ['Pipes & Fittings', 'Faucets', 'Valves', 'Drains', 'Plumbing Fixtures'],
        Electrical: [
          'Wires & Cables',
          'Switches & Outlets',
          'Circuit Protection',
          'Electrical Boxes',
          'Electrical Accessories',
        ],
        'Cleaning & Household': [
          'Cleaning Products',
          'Laundry Products',
          'Cleaning Tools',
          'Household Supplies',
          'Waste Management',
        ],
        'Garden & Outdoor': [
          'Garden Tools',
          'Outdoor Equipment',
          'Gardening Supplies',
          'Pots & Planters',
          'Outdoor Storage',
        ],
        'Plants & Flowers': [
          'Indoor Plants',
          'Outdoor Plants',
          'Flowering Plants',
          'Cut Flowers',
          'Seeds & Bulbs',
        ],
        'Home Safety': [
          'Smoke Detectors',
          'Fire Safety',
          'Security Devices',
          'First Aid Supplies',
          'Safety Equipment',
        ],
      },
    },
    {
      name: 'Health & Wellness',
      description: 'Pharmacies, medical suppliers, and fitness product retailers',
      children: {
        Medicines: [
          'Pain Relief',
          'Cold & Allergy',
          'Digestive Health',
          'Topical Medicines',
          'Prescription Medicines',
        ],
        'Medical Supplies': [
          'Syringes & Needles',
          'Medical Gloves',
          'Medical Masks',
          'Medical Dressings',
          'Medical Consumables',
        ],
        'Medical Devices': [
          'Blood Pressure Monitors',
          'Thermometers',
          'Blood Glucose Monitors',
          'Pulse Oximeters',
          'Diagnostic Devices',
        ],
        'First Aid': [
          'First Aid Kits',
          'Bandages & Dressings',
          'Antiseptics',
          'Wound Care',
          'First Aid Tools',
        ],
        'Vitamins & Supplements': [
          'Vitamins',
          'Minerals',
          'Herbal Supplements',
          'Multivitamins',
          'Specialty Supplements',
        ],
        'Personal Care': [
          'Deodorants',
          'Shaving Products',
          'Feminine Care',
          'Body Care',
          'Personal Hygiene',
        ],
        'Oral Care': ['Toothbrushes', 'Toothpaste', 'Mouthwash', 'Dental Floss', 'Oral Care Tools'],
        'Vision Care': ['Eyeglasses', 'Contact Lenses', 'Reading Glasses', 'Lens Care Products'],
        'Hearing Care': ['Hearing Aids', 'Hearing Aid Accessories', 'Ear Care Products'],
        'Mobility & Support': ['Canes', 'Crutches', 'Walkers', 'Wheelchairs', 'Braces & Supports'],
        'Fitness Equipment': [
          'Cardio Equipment',
          'Strength Equipment',
          'Weight Training',
          'Exercise Machines',
          'Yoga Equipment',
        ],
        'Sports Nutrition': [
          'Protein Products',
          'Energy Products',
          'Electrolytes',
          'Pre-Workout Products',
          'Recovery Products',
        ],
        'Wellness Products': [
          'Massage Products',
          'Aromatherapy',
          'Sleep Products',
          'Relaxation Products',
        ],
        'Hygiene Products': ['Hand Hygiene', 'Sanitary Products', 'Disinfectants', 'Hygiene Kits'],
        'Maternity & Baby Care': [
          'Pregnancy Products',
          'Breastfeeding Products',
          'Baby Hygiene',
          'Baby Health Products',
        ],
        'Elderly Care': [
          'Incontinence Products',
          'Elder Care Supplies',
          'Daily Living Aids',
          'Care Equipment',
        ],
      },
    },
    {
      name: 'Automotive',
      description: 'Vehicles, parts, and automotive products',
      children: {
        Cars: ['Sedans', 'SUVs', 'Hatchbacks', 'Coupes', 'Convertibles', 'Electric Cars'],
        Motorcycles: [
          'Scooters',
          'Standard Motorcycles',
          'Sport Motorcycles',
          'Cruisers',
          'Off-Road Motorcycles',
        ],
        Bicycles: ['Road Bikes', 'Mountain Bikes', 'Hybrid Bikes', 'BMX Bikes', 'Electric Bikes'],
        Trucks: ['Pickup Trucks', 'Light Trucks', 'Heavy Trucks'],
        Vans: ['Passenger Vans', 'Cargo Vans', 'Minivans'],
        'Tires & Wheels': ['Car Tires', 'Motorcycle Tires', 'Bicycle Tires', 'Wheels', 'Rims'],
        'Auto Parts': [
          'Engine Parts',
          'Brake Parts',
          'Suspension Parts',
          'Transmission Parts',
          'Body Parts',
          'Filters',
        ],
        'Motorcycle Parts': [
          'Engine Parts',
          'Brake Parts',
          'Suspension Parts',
          'Body Parts',
          'Exhaust Parts',
        ],
        'Bicycle Parts': ['Frames', 'Brakes', 'Gears & Drivetrain', 'Wheels', 'Bicycle Components'],
        'Car Accessories': [
          'Interior Accessories',
          'Exterior Accessories',
          'Car Electronics',
          'Car Organizers',
          'Comfort Accessories',
        ],
        'Motorcycle Accessories': [
          'Helmets',
          'Riding Gear',
          'Luggage',
          'Protective Gear',
          'Motorcycle Electronics',
        ],
        'Bicycle Accessories': ['Helmets', 'Lights', 'Locks', 'Bags', 'Cycling Computers'],
        'Tools & Equipment': [
          'Hand Tools',
          'Diagnostic Tools',
          'Lifting Equipment',
          'Garage Equipment',
          'Workshop Equipment',
        ],
        'Oils & Fluids': [
          'Engine Oil',
          'Brake Fluid',
          'Coolants',
          'Transmission Fluid',
          'Cleaning Fluids',
        ],
        Batteries: [
          'Car Batteries',
          'Motorcycle Batteries',
          'Electric Vehicle Batteries',
          'Battery Chargers',
        ],
        Lighting: [
          'Headlights',
          'Tail Lights',
          'Signal Lights',
          'Interior Lighting',
          'Auxiliary Lights',
        ],
        'Cleaning & Care': [
          'Car Wash Products',
          'Interior Cleaners',
          'Wax & Polish',
          'Tire Care',
          'Detailing Products',
        ],
        'Safety Equipment': [
          'Safety Kits',
          'Warning Devices',
          'Emergency Equipment',
          'Protective Equipment',
        ],
      },
    },
    {
      name: 'Pets',
      description: 'Pet food, supplies, equipment, and accessories',
      children: {
        'Pet Food': [
          'Dog Food',
          'Cat Food',
          'Bird Food',
          'Fish Food',
          'Small Animal Food',
          'Reptile Food',
        ],
        'Pet Treats': ['Dog Treats', 'Cat Treats', 'Dental Treats', 'Training Treats'],
        'Pet Toys': ['Chew Toys', 'Interactive Toys', 'Plush Toys', 'Balls', 'Fetch Toys'],
        'Pet Supplies': [
          'Feeding Supplies',
          'Training Supplies',
          'Waste Management',
          'Travel Supplies',
        ],
        'Pet Accessories': ['Collars', 'Leashes', 'Harnesses', 'Tags', 'Pet Clothing'],
        'Pet Grooming Products': ['Shampoos', 'Brushes & Combs', 'Nail Care', 'Grooming Tools'],
        'Pet Health Products': [
          'Flea & Tick Products',
          'Supplements',
          'Dental Care',
          'Health Monitoring',
        ],
        'Pet Bedding': ['Pet Beds', 'Blankets', 'Mats', 'Hammocks'],
        'Pet Cages & Enclosures': ['Cages', 'Kennels', 'Crates', 'Habitats'],
        'Aquarium Supplies': [
          'Aquariums',
          'Filters',
          'Water Treatment',
          'Aquarium Lighting',
          'Aquarium Decorations',
        ],
      },
    },
    {
      name: 'Sports & Outdoors',
      description: 'Sporting goods, fitness equipment, and outdoor products',
      children: {
        'Sports Equipment': [
          'Ball Sports Equipment',
          'Racket Sports Equipment',
          'Combat Sports Equipment',
          'Team Sports Equipment',
        ],
        'Fitness Equipment': [
          'Cardio Equipment',
          'Strength Equipment',
          'Free Weights',
          'Exercise Equipment',
        ],
        Sportswear: ['Sports Shirts', 'Sports Shorts', 'Sports Pants', 'Sports Jerseys'],
        'Sports Footwear': ['Running Shoes', 'Training Shoes', 'Court Shoes', 'Cleats'],
        'Sports Accessories': [
          'Sports Bags',
          'Protective Gear',
          'Sports Bottles',
          'Training Accessories',
        ],
        'Camping Equipment': [
          'Tents',
          'Sleeping Bags',
          'Camping Furniture',
          'Camping Cookware',
          'Camping Lighting',
        ],
        'Hiking & Outdoor Gear': [
          'Hiking Bags',
          'Hiking Poles',
          'Outdoor Clothing',
          'Navigation Equipment',
        ],
        'Fishing Equipment': [
          'Fishing Rods',
          'Fishing Reels',
          'Fishing Lines',
          'Fishing Hooks',
          'Fishing Tackle',
        ],
        'Cycling Equipment': [
          'Bicycles',
          'Cycling Helmets',
          'Cycling Bags',
          'Cycling Tools',
          'Cycling Accessories',
        ],
        'Water Sports': [
          'Swimming Equipment',
          'Diving Equipment',
          'Surfing Equipment',
          'Kayaking Equipment',
        ],
        'Outdoor Recreation': [
          'Outdoor Games',
          'Recreation Equipment',
          'Picnic Equipment',
          'Outdoor Accessories',
        ],
      },
    },
    {
      name: 'Entertainment',
      description: 'Media, games, hobbies, and creative products',
      children: {
        Music: ['Musical Instruments', 'Vinyl Records', 'CDs', 'Music Accessories'],
        'Movies & Media': ['DVDs', 'Blu-ray Discs', 'Media Collections', 'Media Players'],
        'Video Games': ['Console Games', 'PC Games', 'Game Cards', 'Game Collectibles'],
        'Board Games': ['Strategy Games', 'Card Games', 'Party Games', 'Puzzle Games'],
        'Toys & Games': [
          'Action Figures',
          'Dolls',
          'Building Toys',
          'Educational Toys',
          'Outdoor Toys',
        ],
        Hobbies: ['Model Kits', 'Collecting Supplies', 'DIY Kits', 'Hobby Tools'],
        'Arts & Crafts': [
          'Art Supplies',
          'Craft Supplies',
          'Drawing Materials',
          'Painting Materials',
        ],
        'Musical Instruments': [
          'Guitars',
          'Keyboards',
          'Drums',
          'String Instruments',
          'Wind Instruments',
        ],
        Collectibles: ['Figures', 'Trading Cards', 'Memorabilia', 'Antiques'],
        'Party & Event Supplies': [
          'Party Decorations',
          'Tableware',
          'Party Favors',
          'Event Decorations',
        ],
      },
    },
    {
      name: 'Baby & Kids',
      description: 'Baby, maternity, and children products',
      children: {
        'Baby Clothing': [
          'Bodysuits',
          'Rompers',
          'Baby Tops',
          'Baby Bottoms',
          'Baby Dresses',
          'Baby Sleepwear',
        ],
        'Baby Food': [
          'Infant Formula',
          'Baby Cereals',
          'Baby Purees',
          'Baby Snacks',
          'Baby Drinks',
        ],
        'Baby Care': [
          'Diapers',
          'Baby Wipes',
          'Baby Bath Products',
          'Baby Skincare',
          'Baby Hygiene',
        ],
        'Baby Gear': ['Strollers', 'Car Seats', 'Baby Carriers', 'High Chairs', 'Baby Monitors'],
        'Baby Toys': ['Rattles', 'Teething Toys', 'Activity Toys', 'Educational Toys'],
        'Maternity Products': [
          'Maternity Clothing',
          'Maternity Support',
          'Nursing Products',
          'Pregnancy Accessories',
        ],
        'Kids Clothing': ['Tops', 'Bottoms', 'Dresses', 'Outerwear', 'Sleepwear', 'Activewear'],
        'Kids Footwear': ['Sneakers', 'School Shoes', 'Sandals', 'Boots', 'Slippers'],
        'Kids Accessories': ['Bags', 'Hats', 'Hair Accessories', 'Sunglasses', 'Jewelry'],
        'Kids School Supplies': [
          'Backpacks',
          'Writing Supplies',
          'Art Supplies',
          'School Accessories',
        ],
        'Nursery Products': [
          'Cribs',
          'Nursery Furniture',
          'Bedding',
          'Nursery Decor',
          'Baby Storage',
        ],
      },
    },
    {
      name: 'Agriculture',
      description: 'Farming, gardening, and agricultural products',
      children: {
        Seeds: ['Vegetable Seeds', 'Fruit Seeds', 'Flower Seeds', 'Herb Seeds', 'Grain Seeds'],
        Fertilizers: [
          'Organic Fertilizers',
          'Chemical Fertilizers',
          'Liquid Fertilizers',
          'Granular Fertilizers',
        ],
        'Soil & Growing Media': [
          'Potting Soil',
          'Garden Soil',
          'Compost',
          'Coco Coir',
          'Growing Media',
        ],
        'Farm Tools': ['Hand Tools', 'Cutting Tools', 'Digging Tools', 'Harvesting Tools'],
        'Farm Equipment': [
          'Tractors',
          'Plows',
          'Cultivators',
          'Harvesting Equipment',
          'Farm Machinery',
        ],
        'Irrigation Equipment': [
          'Water Pumps',
          'Drip Irrigation',
          'Sprinklers',
          'Irrigation Pipes',
        ],
        'Animal Feed': [
          'Cattle Feed',
          'Poultry Feed',
          'Swine Feed',
          'Fish Feed',
          'Pet & Small Animal Feed',
        ],
        'Livestock Supplies': [
          'Animal Housing',
          'Feeding Equipment',
          'Animal Care Supplies',
          'Livestock Equipment',
        ],
        'Crop Protection': ['Pesticides', 'Herbicides', 'Fungicides', 'Organic Crop Protection'],
        'Harvesting Supplies': [
          'Harvesting Tools',
          'Harvest Baskets',
          'Storage Containers',
          'Crop Handling Equipment',
        ],
        'Greenhouse Supplies': [
          'Greenhouses',
          'Growing Trays',
          'Greenhouse Covers',
          'Climate Equipment',
        ],
      },
    },
    {
      name: 'Industrial & Business',
      description: 'Industrial equipment, commercial supplies, and business products',
      children: {
        'Industrial Equipment': [
          'Production Equipment',
          'Processing Equipment',
          'Packaging Equipment',
          'Material Handling Equipment',
        ],
        Machinery: [
          'Manufacturing Machinery',
          'Construction Machinery',
          'Agricultural Machinery',
          'Workshop Machinery',
        ],
        Tools: ['Hand Tools', 'Power Tools', 'Precision Tools', 'Industrial Tools'],
        'Safety Equipment': [
          'Protective Clothing',
          'Head Protection',
          'Eye Protection',
          'Hearing Protection',
          'Respiratory Protection',
        ],
        'Packaging Supplies': ['Boxes', 'Bags', 'Containers', 'Wrapping Materials', 'Labels'],
        'Storage Equipment': ['Shelving', 'Racks', 'Storage Bins', 'Cabinets'],
        'Material Handling': ['Carts', 'Trolleys', 'Pallet Equipment', 'Lifting Equipment'],
        'Cleaning Supplies': [
          'Cleaning Chemicals',
          'Cleaning Tools',
          'Janitorial Equipment',
          'Waste Management',
        ],
        'Commercial Equipment': [
          'Restaurant Equipment',
          'Retail Equipment',
          'Hospitality Equipment',
          'Commercial Refrigeration',
        ],
        'Office Equipment': ['Printers', 'Scanners', 'Copiers', 'Shredders', 'Office Machines'],
        'Wholesale Products': [
          'Bulk Goods',
          'Bulk Packaging',
          'Commercial Supplies',
          'Wholesale Merchandise',
        ],
      },
    },
    {
      // Deliberately a single leaf: this is a fallback for genuinely uncategorizable
      // items, not a dumping ground. Anything that earns a real name belongs under a
      // real root instead.
      name: 'Others',
      description: 'Uncategorized products',
      children: ['Other Products'],
    },
  ];

  let created = 0;
  // Every category this authoring form touches. Used at the end to soft-delete
  // anything in the DB that is no longer part of the taxonomy (e.g. a name removed
  // from the data above). Without this, a stale row survives in the database and
  // keeps showing up in the seller's category picker forever.
  const seededIds = new Set<string>();

  /**
   * Walk a subtree, upserting each node beneath `parentId`.
   *
   * `parentId` is NOT NULL here, so @@unique([parentId, name]) is actually enforced
   * and a real upsert works — unlike roots, where Postgres treats NULL parentIds as
   * distinct and the constraint can never fire (hence the findFirst below).
   */
  const upsertChildren = async (spec: CategorySpec, parentId: string) => {
    const entries: [string, CategorySpec | null][] = Array.isArray(spec)
      ? spec.map((name) => [name, null])
      : Object.entries(spec);

    for (const [name, subtree] of entries) {
      const node = await prisma.categories.upsert({
        where: { parentId_name: { parentId, name } },
        update: {},
        create: { name, parentId },
      });
      created += 1;
      seededIds.add(node.id);

      if (subtree) await upsertChildren(subtree, node.id);
    }
  };

  for (const parent of categoriesToSeed) {
    let rootCategory = await prisma.categories.findFirst({
      where: { name: parent.name, parentId: null },
    });

    if (rootCategory) {
      rootCategory = await prisma.categories.update({
        where: { id: rootCategory.id },
        data: { description: parent.description },
      });
    } else {
      rootCategory = await prisma.categories.create({
        data: {
          name: parent.name,
          description: parent.description,
        },
      });
    }
    created += 1;
    seededIds.add(rootCategory.id);

    await prisma.commissionRules.upsert({
      where: { categoryId: rootCategory.id },
      update: { commissionRate: 0.05, fixedFee: 10.0 },
      create: {
        categoryId: rootCategory.id,
        commissionRate: 0.05,
        fixedFee: 10.0,
        isActive: true,
      },
    });

    await upsertChildren(parent.children, rootCategory.id);
  }

  // Prune anything not part of this taxonomy. Soft-delete rather than hard-delete:
  // categories are referenced by products/stores (FKs are ON DELETE SET NULL), and
  // the app already treats a `deletedAt` timestamp as "hidden" everywhere (every
  // list query filters `deletedAt: null`). This removes the stale rows from the
  // seller's picker without orphaning related rows.
  const pruned = await prisma.categories.updateMany({
    where: { id: { notIn: [...seededIds] }, deletedAt: null },
    data: { deletedAt: new Date() },
  });

  console.log(
    `✅ Global hierarchical categories seeded! (${categoriesToSeed.length} roots, ${created} nodes total` +
      (pruned.count > 0 ? `, pruned ${pruned.count} stale` : '') +
      ')',
  );
}
