-- CreateEnum
CREATE TYPE "MARKERDISPLAYMODE" AS ENUM ('PHOTO_CARD', 'PRICE_CARD', 'LABEL_CARD');

-- AlterTable
ALTER TABLE "Stores" ADD COLUMN     "markerDisplayMode" "MARKERDISPLAYMODE" NOT NULL DEFAULT 'PHOTO_CARD',
ADD COLUMN     "markerPrice" DECIMAL(12,2),
ADD COLUMN     "markerSubtitle" TEXT;
