-- CreateEnum
CREATE TYPE "MERCHANTDISCOUNTTYPE" AS ENUM ('BOGO', 'PERCENTAGE', 'FIXED_AMOUNT');

-- AlterTable
ALTER TABLE "MerchantAds" ADD COLUMN     "discountType" "MERCHANTDISCOUNTTYPE",
ADD COLUMN     "discountValue" DECIMAL(12,2);
